# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pray_petitions', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PrayPetition. As you add validations to PrayPetition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PrayPetition.create! valid_attributes
      get pray_petitions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      pray_petition = PrayPetition.create! valid_attributes
      get pray_petition_url(pray_petition)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_pray_petition_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      pray_petition = PrayPetition.create! valid_attributes
      get edit_pray_petition_url(pray_petition)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PrayPetition' do
        expect do
          post pray_petitions_url, params: { pray_petition: valid_attributes }
        end.to change(PrayPetition, :count).by(1)
      end

      it 'redirects to the created pray_petition' do
        post pray_petitions_url, params: { pray_petition: valid_attributes }
        expect(response).to redirect_to(pray_petition_url(PrayPetition.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PrayPetition' do
        expect do
          post pray_petitions_url, params: { pray_petition: invalid_attributes }
        end.to change(PrayPetition, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pray_petitions_url, params: { pray_petition: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested pray_petition' do
        pray_petition = PrayPetition.create! valid_attributes
        patch pray_petition_url(pray_petition), params: { pray_petition: new_attributes }
        pray_petition.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pray_petition' do
        pray_petition = PrayPetition.create! valid_attributes
        patch pray_petition_url(pray_petition), params: { pray_petition: new_attributes }
        pray_petition.reload
        expect(response).to redirect_to(pray_petition_url(pray_petition))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pray_petition = PrayPetition.create! valid_attributes
        patch pray_petition_url(pray_petition), params: { pray_petition: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested pray_petition' do
      pray_petition = PrayPetition.create! valid_attributes
      expect do
        delete pray_petition_url(pray_petition)
      end.to change(PrayPetition, :count).by(-1)
    end

    it 'redirects to the pray_petitions list' do
      pray_petition = PrayPetition.create! valid_attributes
      delete pray_petition_url(pray_petition)
      expect(response).to redirect_to(pray_petitions_url)
    end
  end
end
